### ISSUE TITLE
How to configure database?

### ISSUE THREAD

**Issue by stereobooster** [astzweig/docker-primecms#1]
I cloned repo. Added `docker-compose.yml`

```yaml
version: "3"

services:
  prime:
    build: .
```

```sh
docker-compose up
...
prime_1  | (node:13) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:5432
prime_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
prime_1  | (node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
prime_1  | (node:13) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I can add postgres to compose

```yaml
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/data/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
```

but how to configure prime?
